### PR TITLE
fix for recurring full day events east of UTC

### LINKED ISSUE #36: full day repeating rule event east of utc get initial date wrong.
seems rrule and luxon disagree on date format rrule for UTC and Luxon for local time

### PR DESCRIPTION
**Pull request by sdetweil**
fix #36

### CODE REVIEW

**Comment by sdetweil** [comment]
lint forced change to includes from indexOf.. I didn't check the results of the function.. 'assumed' it was the same... not..

**Comment by jens-maus** [comment]
Thanks for the new PR. this looks much cleaner. The only thing missing is, that you please should add a new dedicated test for your particular change/enhancement so that in future npm test will test your fix and no further regression happens in case another change might bring back an issue again. So please add a new testcase to this PR.

File: test/test-async.js [hunk 1]
```diff
@@ -3,7 +3,7 @@
  *
  *
  ** */
-process.env.TZ = 'America/San_Francisco';
+process.env.TZ = 'Europe/Zurich';
```
Comment (jens-maus) [inline test/test-async.js]: Why do you need to change to "Europe/Zurich" here?

File: test/test-async.js [hunk 2]
```diff
@@ -559,9 +559,9 @@ vows
         },
         'has a start'(topic) {
           assert.equal(topic.start.tz, '(UTC+07:00) Bangkok, Hanoi, Jakarta');
-          assert.equal(topic.start.toISOString(), new Date(2019, 3, 30, 2, 0, 0).toISOString());
+          assert.equal(topic.end.toISOString().slice(0, 8), new Date(Date.UTC(2019, 3, 30, 9, 0, 0)).toISOString().slice(0, 8));
           assert.equal(topic.end.tz, '(UTC+07:00) Bangkok, Hanoi, Jakarta');
-          assert.equal(topic.end.toISOString(), new Date(2019, 3, 30, 5, 0, 0).toISOString());
+          assert.equal(topic.end.toISOString().slice(0, 8), new Date(2019, 3, 30, 5, 0, 0).toISOString().slice(0, 8));
         }
```
Comment (jens-maus) [inline test/test-async.js:566]: Why did you modify the test15.ics test also?

File: test/test-async.js (hunk 1 above)
Comment (sdetweil) [reply test/test-async.js]: as full day events don't have a timezone, the problem only occurs when the current time is east of UTC. 

I couldn't find a way to change the timezone just for this test..

File: test/test-async.js (hunk 2 above)
Comment (sdetweil) [reply test/test-async.js:566]: I had changed it for test.js in a prior change.. it is impacted by the same problem as current.. 
the original testcase was comparing date, so I made it ignore time

File: test/test-async.js (hunk 1 above)
Comment (jens-maus) [reply test/test-async.js]: Have you tried `moment.tz.setDefault(String)`? See:

https://momentjs.com/timezone/docs/#/using-timezones/default-timezone/

File: test/test-async.js (hunk 2 above)
Comment (jens-maus) [reply test/test-async.js:566]: Ok. thanks.

File: test/test-async.js (hunk 1 above)
Comment (sdetweil) [reply test/test-async.js]: how do you do that in testcase was the problem

Comment (jens-maus) [reply test/test-async.js]: what about this? Did you test this?

```diff
--- a/test/test.js
+++ b/test/test.js
@@ -3,18 +3,18 @@
  *
  *
  ** */
-process.env.TZ = 'America/San_Francisco';
-
 const assert = require('assert');
 const vows = require('vows');
 const _ = require('underscore');
 const ical = require('../node-ical');
+const moment = require('moment-timezone');
 
 vows
   .describe('node-ical')
   .addBatch({
     'when parsing test1.ics (node conferences schedule from lanyrd.com, modified)': {
       topic() {
+        moment.tz.setDefault('America/San_Francisco');
         return ical.parseFile('./test/test1.ics');
       },
```

Comment (sdetweil) [reply test/test-async.js]: No. didn't know that you could do that.. I looked all over.. don't know vows, nothing in the doc implies u can do that

Comment (jens-maus) [reply test/test-async.js]: I am not sure if this works or not because it could be that the setDefault only works for the moment object, but I prefer try&error here. So see if you can change it accordingly and if it works. then use that method to change the timezone only for the new testcase.

**Comment by jens-maus** [comment]
perfect! thanks for the nice contribution!

**Comment by sdetweil** [comment]
should be 12.3, right? as u already published 12.2

**Comment by jens-maus** [comment]
yes, as soon as I will publish 0.12.3 this change will be included. I am just hoping someone can take care of #14 so that I can release it ASAP.

**Comment by sdetweil** [comment]
got it.. we have a matching issue, but haven't been able to get anyone to send a testcase that actually fails.
I would fix it, as soon as I see a testcase
